# Generated by Django 5.2.1 on 2025-05-30 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_remove_reservation_pet_name_remove_reservation_time_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
