# Generated by Django 5.2.1 on 2025-05-30 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0003_delete_reservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroomingAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('contact_number', models.CharField(max_length=15)),
                ('grooming_package', models.CharField(choices=[('Basic Bath', 'Basic Bath'), ('Full Groom', 'Full Groom'), ('Nail Trim', 'Nail Trim'), ('Ear Cleaning', 'Ear Cleaning')], max_length=100)),
                ('add_ons', models.CharField(blank=True, max_length=255)),
                ('coat_type', models.CharField(max_length=100)),
                ('behavior_notes', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VeterinaryAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(max_length=100)),
                ('pet_type', models.CharField(choices=[('Dog', 'Dog'), ('Cat', 'Cat')], max_length=50)),
                ('breed', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.TimeField()),
                ('contact_number', models.CharField(max_length=15)),
                ('visit_type', models.CharField(choices=[('Check-up', 'Check-up'), ('Vaccination', 'Vaccination'), ('Illness', 'Illness'), ('Surgery', 'Surgery'), ('Emergency', 'Emergency')], max_length=100)),
                ('symptoms', models.TextField()),
                ('current_medications', models.CharField(blank=True, max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
