# Generated by Django 5.2.1 on 2025-05-31 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_groomingappointment_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groomingappointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Canceled', 'Canceled')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='veterinaryappointment',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Canceled', 'Canceled')], default='pending', max_length=10),
        ),
    ]
