# Generated by Django 5.2.1 on 2025-06-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_alter_groomingappointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groomingappointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='veterinaryappointment',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
